id: IEAA2F09F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T12:05:21+00:00'
last_modified: '2022-06-07T17:38:13.749329+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG01597
  title: གཤིན་རྗེ་གཤེད་ཀྱི་འཁྲུལ་འཁོར་སྐབས་ཀྱི་ཕྱག་ལེན་ཟིན་ཆུང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedSealed
  restrictedInChina: false
  base:
    '9171':
      image_group_id: I1CZ2057
      title: ''
      total_pages: 20
      order: 1
      base_file: 9171.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
